// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_answer.proto

package via.dk.elearn.protobuf;

/**
 * Protobuf type {@code AnswerModel}
 */
public final class AnswerModel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AnswerModel)
    AnswerModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnswerModel.newBuilder() to construct.
  private AnswerModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnswerModel() {
    text_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnswerModel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnswerModel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            via.dk.elearn.protobuf.UserModel.Builder subBuilder = null;
            if (author_ != null) {
              subBuilder = author_.toBuilder();
            }
            author_ = input.readMessage(via.dk.elearn.protobuf.UserModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(author_);
              author_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            via.dk.elearn.protobuf.QuestionModel.Builder subBuilder = null;
            if (question_ != null) {
              subBuilder = question_.toBuilder();
            }
            question_ = input.readMessage(via.dk.elearn.protobuf.QuestionModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(question_);
              question_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          case 42: {
            via.dk.elearn.protobuf.DateModel.Builder subBuilder = null;
            if (date_ != null) {
              subBuilder = date_.toBuilder();
            }
            date_ = input.readMessage(via.dk.elearn.protobuf.DateModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(date_);
              date_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            correct_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.dk.elearn.protobuf.RpcAnswer.internal_static_AnswerModel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.dk.elearn.protobuf.RpcAnswer.internal_static_AnswerModel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.dk.elearn.protobuf.AnswerModel.class, via.dk.elearn.protobuf.AnswerModel.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int AUTHOR_FIELD_NUMBER = 2;
  private via.dk.elearn.protobuf.UserModel author_;
  /**
   * <code>.UserModel author = 2;</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return author_ != null;
  }
  /**
   * <code>.UserModel author = 2;</code>
   * @return The author.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.UserModel getAuthor() {
    return author_ == null ? via.dk.elearn.protobuf.UserModel.getDefaultInstance() : author_;
  }
  /**
   * <code>.UserModel author = 2;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.UserModelOrBuilder getAuthorOrBuilder() {
    return getAuthor();
  }

  public static final int QUESTION_FIELD_NUMBER = 3;
  private via.dk.elearn.protobuf.QuestionModel question_;
  /**
   * <code>.QuestionModel question = 3;</code>
   * @return Whether the question field is set.
   */
  @java.lang.Override
  public boolean hasQuestion() {
    return question_ != null;
  }
  /**
   * <code>.QuestionModel question = 3;</code>
   * @return The question.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.QuestionModel getQuestion() {
    return question_ == null ? via.dk.elearn.protobuf.QuestionModel.getDefaultInstance() : question_;
  }
  /**
   * <code>.QuestionModel question = 3;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.QuestionModelOrBuilder getQuestionOrBuilder() {
    return getQuestion();
  }

  public static final int TEXT_FIELD_NUMBER = 4;
  private volatile java.lang.Object text_;
  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 5;
  private via.dk.elearn.protobuf.DateModel date_;
  /**
   * <code>.DateModel date = 5;</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.DateModel date = 5;</code>
   * @return The date.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.DateModel getDate() {
    return date_ == null ? via.dk.elearn.protobuf.DateModel.getDefaultInstance() : date_;
  }
  /**
   * <code>.DateModel date = 5;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.DateModelOrBuilder getDateOrBuilder() {
    return getDate();
  }

  public static final int CORRECT_FIELD_NUMBER = 6;
  private boolean correct_;
  /**
   * <code>bool correct = 6;</code>
   * @return The correct.
   */
  @java.lang.Override
  public boolean getCorrect() {
    return correct_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (author_ != null) {
      output.writeMessage(2, getAuthor());
    }
    if (question_ != null) {
      output.writeMessage(3, getQuestion());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, text_);
    }
    if (date_ != null) {
      output.writeMessage(5, getDate());
    }
    if (correct_ != false) {
      output.writeBool(6, correct_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (author_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAuthor());
    }
    if (question_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getQuestion());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, text_);
    }
    if (date_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDate());
    }
    if (correct_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, correct_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.dk.elearn.protobuf.AnswerModel)) {
      return super.equals(obj);
    }
    via.dk.elearn.protobuf.AnswerModel other = (via.dk.elearn.protobuf.AnswerModel) obj;

    if (getId()
        != other.getId()) return false;
    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (hasQuestion() != other.hasQuestion()) return false;
    if (hasQuestion()) {
      if (!getQuestion()
          .equals(other.getQuestion())) return false;
    }
    if (!getText()
        .equals(other.getText())) return false;
    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (getCorrect()
        != other.getCorrect()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    if (hasQuestion()) {
      hash = (37 * hash) + QUESTION_FIELD_NUMBER;
      hash = (53 * hash) + getQuestion().hashCode();
    }
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    hash = (37 * hash) + CORRECT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCorrect());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.AnswerModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.dk.elearn.protobuf.AnswerModel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnswerModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnswerModel)
      via.dk.elearn.protobuf.AnswerModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.dk.elearn.protobuf.RpcAnswer.internal_static_AnswerModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.dk.elearn.protobuf.RpcAnswer.internal_static_AnswerModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.dk.elearn.protobuf.AnswerModel.class, via.dk.elearn.protobuf.AnswerModel.Builder.class);
    }

    // Construct using via.dk.elearn.protobuf.AnswerModel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (authorBuilder_ == null) {
        author_ = null;
      } else {
        author_ = null;
        authorBuilder_ = null;
      }
      if (questionBuilder_ == null) {
        question_ = null;
      } else {
        question_ = null;
        questionBuilder_ = null;
      }
      text_ = "";

      if (dateBuilder_ == null) {
        date_ = null;
      } else {
        date_ = null;
        dateBuilder_ = null;
      }
      correct_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.dk.elearn.protobuf.RpcAnswer.internal_static_AnswerModel_descriptor;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.AnswerModel getDefaultInstanceForType() {
      return via.dk.elearn.protobuf.AnswerModel.getDefaultInstance();
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.AnswerModel build() {
      via.dk.elearn.protobuf.AnswerModel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.AnswerModel buildPartial() {
      via.dk.elearn.protobuf.AnswerModel result = new via.dk.elearn.protobuf.AnswerModel(this);
      result.id_ = id_;
      if (authorBuilder_ == null) {
        result.author_ = author_;
      } else {
        result.author_ = authorBuilder_.build();
      }
      if (questionBuilder_ == null) {
        result.question_ = question_;
      } else {
        result.question_ = questionBuilder_.build();
      }
      result.text_ = text_;
      if (dateBuilder_ == null) {
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      result.correct_ = correct_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.dk.elearn.protobuf.AnswerModel) {
        return mergeFrom((via.dk.elearn.protobuf.AnswerModel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.dk.elearn.protobuf.AnswerModel other) {
      if (other == via.dk.elearn.protobuf.AnswerModel.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasAuthor()) {
        mergeAuthor(other.getAuthor());
      }
      if (other.hasQuestion()) {
        mergeQuestion(other.getQuestion());
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      if (other.getCorrect() != false) {
        setCorrect(other.getCorrect());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.dk.elearn.protobuf.AnswerModel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.dk.elearn.protobuf.AnswerModel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.UserModel author_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.UserModel, via.dk.elearn.protobuf.UserModel.Builder, via.dk.elearn.protobuf.UserModelOrBuilder> authorBuilder_;
    /**
     * <code>.UserModel author = 2;</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return authorBuilder_ != null || author_ != null;
    }
    /**
     * <code>.UserModel author = 2;</code>
     * @return The author.
     */
    public via.dk.elearn.protobuf.UserModel getAuthor() {
      if (authorBuilder_ == null) {
        return author_ == null ? via.dk.elearn.protobuf.UserModel.getDefaultInstance() : author_;
      } else {
        return authorBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder setAuthor(via.dk.elearn.protobuf.UserModel value) {
      if (authorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;
        onChanged();
      } else {
        authorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder setAuthor(
        via.dk.elearn.protobuf.UserModel.Builder builderForValue) {
      if (authorBuilder_ == null) {
        author_ = builderForValue.build();
        onChanged();
      } else {
        authorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder mergeAuthor(via.dk.elearn.protobuf.UserModel value) {
      if (authorBuilder_ == null) {
        if (author_ != null) {
          author_ =
            via.dk.elearn.protobuf.UserModel.newBuilder(author_).mergeFrom(value).buildPartial();
        } else {
          author_ = value;
        }
        onChanged();
      } else {
        authorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder clearAuthor() {
      if (authorBuilder_ == null) {
        author_ = null;
        onChanged();
      } else {
        author_ = null;
        authorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public via.dk.elearn.protobuf.UserModel.Builder getAuthorBuilder() {
      
      onChanged();
      return getAuthorFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public via.dk.elearn.protobuf.UserModelOrBuilder getAuthorOrBuilder() {
      if (authorBuilder_ != null) {
        return authorBuilder_.getMessageOrBuilder();
      } else {
        return author_ == null ?
            via.dk.elearn.protobuf.UserModel.getDefaultInstance() : author_;
      }
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.UserModel, via.dk.elearn.protobuf.UserModel.Builder, via.dk.elearn.protobuf.UserModelOrBuilder> 
        getAuthorFieldBuilder() {
      if (authorBuilder_ == null) {
        authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.UserModel, via.dk.elearn.protobuf.UserModel.Builder, via.dk.elearn.protobuf.UserModelOrBuilder>(
                getAuthor(),
                getParentForChildren(),
                isClean());
        author_ = null;
      }
      return authorBuilder_;
    }

    private via.dk.elearn.protobuf.QuestionModel question_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.QuestionModel, via.dk.elearn.protobuf.QuestionModel.Builder, via.dk.elearn.protobuf.QuestionModelOrBuilder> questionBuilder_;
    /**
     * <code>.QuestionModel question = 3;</code>
     * @return Whether the question field is set.
     */
    public boolean hasQuestion() {
      return questionBuilder_ != null || question_ != null;
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     * @return The question.
     */
    public via.dk.elearn.protobuf.QuestionModel getQuestion() {
      if (questionBuilder_ == null) {
        return question_ == null ? via.dk.elearn.protobuf.QuestionModel.getDefaultInstance() : question_;
      } else {
        return questionBuilder_.getMessage();
      }
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     */
    public Builder setQuestion(via.dk.elearn.protobuf.QuestionModel value) {
      if (questionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        question_ = value;
        onChanged();
      } else {
        questionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     */
    public Builder setQuestion(
        via.dk.elearn.protobuf.QuestionModel.Builder builderForValue) {
      if (questionBuilder_ == null) {
        question_ = builderForValue.build();
        onChanged();
      } else {
        questionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     */
    public Builder mergeQuestion(via.dk.elearn.protobuf.QuestionModel value) {
      if (questionBuilder_ == null) {
        if (question_ != null) {
          question_ =
            via.dk.elearn.protobuf.QuestionModel.newBuilder(question_).mergeFrom(value).buildPartial();
        } else {
          question_ = value;
        }
        onChanged();
      } else {
        questionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     */
    public Builder clearQuestion() {
      if (questionBuilder_ == null) {
        question_ = null;
        onChanged();
      } else {
        question_ = null;
        questionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     */
    public via.dk.elearn.protobuf.QuestionModel.Builder getQuestionBuilder() {
      
      onChanged();
      return getQuestionFieldBuilder().getBuilder();
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     */
    public via.dk.elearn.protobuf.QuestionModelOrBuilder getQuestionOrBuilder() {
      if (questionBuilder_ != null) {
        return questionBuilder_.getMessageOrBuilder();
      } else {
        return question_ == null ?
            via.dk.elearn.protobuf.QuestionModel.getDefaultInstance() : question_;
      }
    }
    /**
     * <code>.QuestionModel question = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.QuestionModel, via.dk.elearn.protobuf.QuestionModel.Builder, via.dk.elearn.protobuf.QuestionModelOrBuilder> 
        getQuestionFieldBuilder() {
      if (questionBuilder_ == null) {
        questionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.QuestionModel, via.dk.elearn.protobuf.QuestionModel.Builder, via.dk.elearn.protobuf.QuestionModelOrBuilder>(
                getQuestion(),
                getParentForChildren(),
                isClean());
        question_ = null;
      }
      return questionBuilder_;
    }

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 4;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 4;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 4;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <code>string text = 4;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.DateModel date_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder> dateBuilder_;
    /**
     * <code>.DateModel date = 5;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return dateBuilder_ != null || date_ != null;
    }
    /**
     * <code>.DateModel date = 5;</code>
     * @return The date.
     */
    public via.dk.elearn.protobuf.DateModel getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? via.dk.elearn.protobuf.DateModel.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder setDate(via.dk.elearn.protobuf.DateModel value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder setDate(
        via.dk.elearn.protobuf.DateModel.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder mergeDate(via.dk.elearn.protobuf.DateModel value) {
      if (dateBuilder_ == null) {
        if (date_ != null) {
          date_ =
            via.dk.elearn.protobuf.DateModel.newBuilder(date_).mergeFrom(value).buildPartial();
        } else {
          date_ = value;
        }
        onChanged();
      } else {
        dateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = null;
        onChanged();
      } else {
        date_ = null;
        dateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public via.dk.elearn.protobuf.DateModel.Builder getDateBuilder() {
      
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public via.dk.elearn.protobuf.DateModelOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            via.dk.elearn.protobuf.DateModel.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }

    private boolean correct_ ;
    /**
     * <code>bool correct = 6;</code>
     * @return The correct.
     */
    @java.lang.Override
    public boolean getCorrect() {
      return correct_;
    }
    /**
     * <code>bool correct = 6;</code>
     * @param value The correct to set.
     * @return This builder for chaining.
     */
    public Builder setCorrect(boolean value) {
      
      correct_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool correct = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrect() {
      
      correct_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AnswerModel)
  }

  // @@protoc_insertion_point(class_scope:AnswerModel)
  private static final via.dk.elearn.protobuf.AnswerModel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.dk.elearn.protobuf.AnswerModel();
  }

  public static via.dk.elearn.protobuf.AnswerModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnswerModel>
      PARSER = new com.google.protobuf.AbstractParser<AnswerModel>() {
    @java.lang.Override
    public AnswerModel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnswerModel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnswerModel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnswerModel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.dk.elearn.protobuf.AnswerModel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

