// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_answer.proto

package via.dk.elearn.protobuf;

public interface AnswerModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnswerModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.UserModel author = 2;</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <code>.UserModel author = 2;</code>
   * @return The author.
   */
  via.dk.elearn.protobuf.UserModel getAuthor();
  /**
   * <code>.UserModel author = 2;</code>
   */
  via.dk.elearn.protobuf.UserModelOrBuilder getAuthorOrBuilder();

  /**
   * <code>.QuestionModel question = 3;</code>
   * @return Whether the question field is set.
   */
  boolean hasQuestion();
  /**
   * <code>.QuestionModel question = 3;</code>
   * @return The question.
   */
  via.dk.elearn.protobuf.QuestionModel getQuestion();
  /**
   * <code>.QuestionModel question = 3;</code>
   */
  via.dk.elearn.protobuf.QuestionModelOrBuilder getQuestionOrBuilder();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>.DateModel date = 5;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.DateModel date = 5;</code>
   * @return The date.
   */
  via.dk.elearn.protobuf.DateModel getDate();
  /**
   * <code>.DateModel date = 5;</code>
   */
  via.dk.elearn.protobuf.DateModelOrBuilder getDateOrBuilder();

  /**
   * <code>bool correct = 6;</code>
   * @return The correct.
   */
  boolean getCorrect();
}
