// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_comment.proto

package via.dk.elearn.protobuf;

/**
 * Protobuf type {@code CommentModel}
 */
public final class CommentModel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CommentModel)
    CommentModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommentModel.newBuilder() to construct.
  private CommentModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommentModel() {
    text_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommentModel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommentModel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            via.dk.elearn.protobuf.UserModel.Builder subBuilder = null;
            if (author_ != null) {
              subBuilder = author_.toBuilder();
            }
            author_ = input.readMessage(via.dk.elearn.protobuf.UserModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(author_);
              author_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            via.dk.elearn.protobuf.LectureModel.Builder subBuilder = null;
            if (lecture_ != null) {
              subBuilder = lecture_.toBuilder();
            }
            lecture_ = input.readMessage(via.dk.elearn.protobuf.LectureModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lecture_);
              lecture_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            text_ = s;
            break;
          }
          case 42: {
            via.dk.elearn.protobuf.DateModel.Builder subBuilder = null;
            if (date_ != null) {
              subBuilder = date_.toBuilder();
            }
            date_ = input.readMessage(via.dk.elearn.protobuf.DateModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(date_);
              date_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.dk.elearn.protobuf.RpcComment.internal_static_CommentModel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.dk.elearn.protobuf.RpcComment.internal_static_CommentModel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.dk.elearn.protobuf.CommentModel.class, via.dk.elearn.protobuf.CommentModel.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int AUTHOR_FIELD_NUMBER = 2;
  private via.dk.elearn.protobuf.UserModel author_;
  /**
   * <code>.UserModel author = 2;</code>
   * @return Whether the author field is set.
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return author_ != null;
  }
  /**
   * <code>.UserModel author = 2;</code>
   * @return The author.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.UserModel getAuthor() {
    return author_ == null ? via.dk.elearn.protobuf.UserModel.getDefaultInstance() : author_;
  }
  /**
   * <code>.UserModel author = 2;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.UserModelOrBuilder getAuthorOrBuilder() {
    return getAuthor();
  }

  public static final int LECTURE_FIELD_NUMBER = 3;
  private via.dk.elearn.protobuf.LectureModel lecture_;
  /**
   * <code>.LectureModel lecture = 3;</code>
   * @return Whether the lecture field is set.
   */
  @java.lang.Override
  public boolean hasLecture() {
    return lecture_ != null;
  }
  /**
   * <code>.LectureModel lecture = 3;</code>
   * @return The lecture.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.LectureModel getLecture() {
    return lecture_ == null ? via.dk.elearn.protobuf.LectureModel.getDefaultInstance() : lecture_;
  }
  /**
   * <code>.LectureModel lecture = 3;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.LectureModelOrBuilder getLectureOrBuilder() {
    return getLecture();
  }

  public static final int TEXT_FIELD_NUMBER = 4;
  private volatile java.lang.Object text_;
  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 5;
  private via.dk.elearn.protobuf.DateModel date_;
  /**
   * <code>.DateModel date = 5;</code>
   * @return Whether the date field is set.
   */
  @java.lang.Override
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.DateModel date = 5;</code>
   * @return The date.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.DateModel getDate() {
    return date_ == null ? via.dk.elearn.protobuf.DateModel.getDefaultInstance() : date_;
  }
  /**
   * <code>.DateModel date = 5;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.DateModelOrBuilder getDateOrBuilder() {
    return getDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (author_ != null) {
      output.writeMessage(2, getAuthor());
    }
    if (lecture_ != null) {
      output.writeMessage(3, getLecture());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, text_);
    }
    if (date_ != null) {
      output.writeMessage(5, getDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (author_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAuthor());
    }
    if (lecture_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLecture());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, text_);
    }
    if (date_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.dk.elearn.protobuf.CommentModel)) {
      return super.equals(obj);
    }
    via.dk.elearn.protobuf.CommentModel other = (via.dk.elearn.protobuf.CommentModel) obj;

    if (getId()
        != other.getId()) return false;
    if (hasAuthor() != other.hasAuthor()) return false;
    if (hasAuthor()) {
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
    }
    if (hasLecture() != other.hasLecture()) return false;
    if (hasLecture()) {
      if (!getLecture()
          .equals(other.getLecture())) return false;
    }
    if (!getText()
        .equals(other.getText())) return false;
    if (hasDate() != other.hasDate()) return false;
    if (hasDate()) {
      if (!getDate()
          .equals(other.getDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasAuthor()) {
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
    }
    if (hasLecture()) {
      hash = (37 * hash) + LECTURE_FIELD_NUMBER;
      hash = (53 * hash) + getLecture().hashCode();
    }
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.CommentModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.CommentModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.CommentModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.dk.elearn.protobuf.CommentModel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CommentModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CommentModel)
      via.dk.elearn.protobuf.CommentModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.dk.elearn.protobuf.RpcComment.internal_static_CommentModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.dk.elearn.protobuf.RpcComment.internal_static_CommentModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.dk.elearn.protobuf.CommentModel.class, via.dk.elearn.protobuf.CommentModel.Builder.class);
    }

    // Construct using via.dk.elearn.protobuf.CommentModel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (authorBuilder_ == null) {
        author_ = null;
      } else {
        author_ = null;
        authorBuilder_ = null;
      }
      if (lectureBuilder_ == null) {
        lecture_ = null;
      } else {
        lecture_ = null;
        lectureBuilder_ = null;
      }
      text_ = "";

      if (dateBuilder_ == null) {
        date_ = null;
      } else {
        date_ = null;
        dateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.dk.elearn.protobuf.RpcComment.internal_static_CommentModel_descriptor;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.CommentModel getDefaultInstanceForType() {
      return via.dk.elearn.protobuf.CommentModel.getDefaultInstance();
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.CommentModel build() {
      via.dk.elearn.protobuf.CommentModel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.CommentModel buildPartial() {
      via.dk.elearn.protobuf.CommentModel result = new via.dk.elearn.protobuf.CommentModel(this);
      result.id_ = id_;
      if (authorBuilder_ == null) {
        result.author_ = author_;
      } else {
        result.author_ = authorBuilder_.build();
      }
      if (lectureBuilder_ == null) {
        result.lecture_ = lecture_;
      } else {
        result.lecture_ = lectureBuilder_.build();
      }
      result.text_ = text_;
      if (dateBuilder_ == null) {
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.dk.elearn.protobuf.CommentModel) {
        return mergeFrom((via.dk.elearn.protobuf.CommentModel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.dk.elearn.protobuf.CommentModel other) {
      if (other == via.dk.elearn.protobuf.CommentModel.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasAuthor()) {
        mergeAuthor(other.getAuthor());
      }
      if (other.hasLecture()) {
        mergeLecture(other.getLecture());
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        onChanged();
      }
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.dk.elearn.protobuf.CommentModel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.dk.elearn.protobuf.CommentModel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.UserModel author_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.UserModel, via.dk.elearn.protobuf.UserModel.Builder, via.dk.elearn.protobuf.UserModelOrBuilder> authorBuilder_;
    /**
     * <code>.UserModel author = 2;</code>
     * @return Whether the author field is set.
     */
    public boolean hasAuthor() {
      return authorBuilder_ != null || author_ != null;
    }
    /**
     * <code>.UserModel author = 2;</code>
     * @return The author.
     */
    public via.dk.elearn.protobuf.UserModel getAuthor() {
      if (authorBuilder_ == null) {
        return author_ == null ? via.dk.elearn.protobuf.UserModel.getDefaultInstance() : author_;
      } else {
        return authorBuilder_.getMessage();
      }
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder setAuthor(via.dk.elearn.protobuf.UserModel value) {
      if (authorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        author_ = value;
        onChanged();
      } else {
        authorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder setAuthor(
        via.dk.elearn.protobuf.UserModel.Builder builderForValue) {
      if (authorBuilder_ == null) {
        author_ = builderForValue.build();
        onChanged();
      } else {
        authorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder mergeAuthor(via.dk.elearn.protobuf.UserModel value) {
      if (authorBuilder_ == null) {
        if (author_ != null) {
          author_ =
            via.dk.elearn.protobuf.UserModel.newBuilder(author_).mergeFrom(value).buildPartial();
        } else {
          author_ = value;
        }
        onChanged();
      } else {
        authorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public Builder clearAuthor() {
      if (authorBuilder_ == null) {
        author_ = null;
        onChanged();
      } else {
        author_ = null;
        authorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public via.dk.elearn.protobuf.UserModel.Builder getAuthorBuilder() {
      
      onChanged();
      return getAuthorFieldBuilder().getBuilder();
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    public via.dk.elearn.protobuf.UserModelOrBuilder getAuthorOrBuilder() {
      if (authorBuilder_ != null) {
        return authorBuilder_.getMessageOrBuilder();
      } else {
        return author_ == null ?
            via.dk.elearn.protobuf.UserModel.getDefaultInstance() : author_;
      }
    }
    /**
     * <code>.UserModel author = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.UserModel, via.dk.elearn.protobuf.UserModel.Builder, via.dk.elearn.protobuf.UserModelOrBuilder> 
        getAuthorFieldBuilder() {
      if (authorBuilder_ == null) {
        authorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.UserModel, via.dk.elearn.protobuf.UserModel.Builder, via.dk.elearn.protobuf.UserModelOrBuilder>(
                getAuthor(),
                getParentForChildren(),
                isClean());
        author_ = null;
      }
      return authorBuilder_;
    }

    private via.dk.elearn.protobuf.LectureModel lecture_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.LectureModel, via.dk.elearn.protobuf.LectureModel.Builder, via.dk.elearn.protobuf.LectureModelOrBuilder> lectureBuilder_;
    /**
     * <code>.LectureModel lecture = 3;</code>
     * @return Whether the lecture field is set.
     */
    public boolean hasLecture() {
      return lectureBuilder_ != null || lecture_ != null;
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     * @return The lecture.
     */
    public via.dk.elearn.protobuf.LectureModel getLecture() {
      if (lectureBuilder_ == null) {
        return lecture_ == null ? via.dk.elearn.protobuf.LectureModel.getDefaultInstance() : lecture_;
      } else {
        return lectureBuilder_.getMessage();
      }
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     */
    public Builder setLecture(via.dk.elearn.protobuf.LectureModel value) {
      if (lectureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lecture_ = value;
        onChanged();
      } else {
        lectureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     */
    public Builder setLecture(
        via.dk.elearn.protobuf.LectureModel.Builder builderForValue) {
      if (lectureBuilder_ == null) {
        lecture_ = builderForValue.build();
        onChanged();
      } else {
        lectureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     */
    public Builder mergeLecture(via.dk.elearn.protobuf.LectureModel value) {
      if (lectureBuilder_ == null) {
        if (lecture_ != null) {
          lecture_ =
            via.dk.elearn.protobuf.LectureModel.newBuilder(lecture_).mergeFrom(value).buildPartial();
        } else {
          lecture_ = value;
        }
        onChanged();
      } else {
        lectureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     */
    public Builder clearLecture() {
      if (lectureBuilder_ == null) {
        lecture_ = null;
        onChanged();
      } else {
        lecture_ = null;
        lectureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     */
    public via.dk.elearn.protobuf.LectureModel.Builder getLectureBuilder() {
      
      onChanged();
      return getLectureFieldBuilder().getBuilder();
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     */
    public via.dk.elearn.protobuf.LectureModelOrBuilder getLectureOrBuilder() {
      if (lectureBuilder_ != null) {
        return lectureBuilder_.getMessageOrBuilder();
      } else {
        return lecture_ == null ?
            via.dk.elearn.protobuf.LectureModel.getDefaultInstance() : lecture_;
      }
    }
    /**
     * <code>.LectureModel lecture = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.LectureModel, via.dk.elearn.protobuf.LectureModel.Builder, via.dk.elearn.protobuf.LectureModelOrBuilder> 
        getLectureFieldBuilder() {
      if (lectureBuilder_ == null) {
        lectureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.LectureModel, via.dk.elearn.protobuf.LectureModel.Builder, via.dk.elearn.protobuf.LectureModelOrBuilder>(
                getLecture(),
                getParentForChildren(),
                isClean());
        lecture_ = null;
      }
      return lectureBuilder_;
    }

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 4;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 4;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 4;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      
      text_ = getDefaultInstance().getText();
      onChanged();
      return this;
    }
    /**
     * <code>string text = 4;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      text_ = value;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.DateModel date_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder> dateBuilder_;
    /**
     * <code>.DateModel date = 5;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return dateBuilder_ != null || date_ != null;
    }
    /**
     * <code>.DateModel date = 5;</code>
     * @return The date.
     */
    public via.dk.elearn.protobuf.DateModel getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? via.dk.elearn.protobuf.DateModel.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder setDate(via.dk.elearn.protobuf.DateModel value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder setDate(
        via.dk.elearn.protobuf.DateModel.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder mergeDate(via.dk.elearn.protobuf.DateModel value) {
      if (dateBuilder_ == null) {
        if (date_ != null) {
          date_ =
            via.dk.elearn.protobuf.DateModel.newBuilder(date_).mergeFrom(value).buildPartial();
        } else {
          date_ = value;
        }
        onChanged();
      } else {
        dateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = null;
        onChanged();
      } else {
        date_ = null;
        dateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public via.dk.elearn.protobuf.DateModel.Builder getDateBuilder() {
      
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    public via.dk.elearn.protobuf.DateModelOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            via.dk.elearn.protobuf.DateModel.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.DateModel date = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CommentModel)
  }

  // @@protoc_insertion_point(class_scope:CommentModel)
  private static final via.dk.elearn.protobuf.CommentModel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.dk.elearn.protobuf.CommentModel();
  }

  public static via.dk.elearn.protobuf.CommentModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommentModel>
      PARSER = new com.google.protobuf.AbstractParser<CommentModel>() {
    @java.lang.Override
    public CommentModel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommentModel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommentModel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommentModel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.dk.elearn.protobuf.CommentModel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

