// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_country.proto

package via.dk.elearn.protobuf;

public interface CountryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CountryRequest)
    com.google.protobuf.MessageOrBuilder {
}
