// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_country.proto

package via.dk.elearn.protobuf;

public interface CountryModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CountryModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
