// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_date.proto

package via.dk.elearn.protobuf;

public interface DateModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DateModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   * @return The day.
   */
  int getDay();

  /**
   * <code>int32 hour = 4;</code>
   * @return The hour.
   */
  int getHour();

  /**
   * <code>int32 minute = 5;</code>
   * @return The minute.
   */
  int getMinute();

  /**
   * <code>int32 second = 6;</code>
   * @return The second.
   */
  int getSecond();
}
