// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_lecture.proto

package via.dk.elearn.protobuf;

public interface LectureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LectureResponse)
    com.google.protobuf.MessageOrBuilder {
}
