// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_lecture.proto

package via.dk.elearn.protobuf;

public interface LectureUrlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LectureUrl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
