// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_lecture.proto

package via.dk.elearn.protobuf;

public interface LectureModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LectureModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string body = 2;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 2;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string url = 4;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 4;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string image = 5;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 5;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>string description = 6;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 6;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>.TeacherModel teacher = 7;</code>
   * @return Whether the teacher field is set.
   */
  boolean hasTeacher();
  /**
   * <code>.TeacherModel teacher = 7;</code>
   * @return The teacher.
   */
  via.dk.elearn.protobuf.TeacherModel getTeacher();
  /**
   * <code>.TeacherModel teacher = 7;</code>
   */
  via.dk.elearn.protobuf.TeacherModelOrBuilder getTeacherOrBuilder();

  /**
   * <code>.DateModel date = 8;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.DateModel date = 8;</code>
   * @return The date.
   */
  via.dk.elearn.protobuf.DateModel getDate();
  /**
   * <code>.DateModel date = 8;</code>
   */
  via.dk.elearn.protobuf.DateModelOrBuilder getDateOrBuilder();
}
