// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_user.proto

package via.dk.elearn.protobuf;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
