// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_answer.proto

package via.dk.elearn.protobuf;

public interface NewAnswerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NewAnswerRequest)
    com.google.protobuf.MessageOrBuilder {
}
