// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_comment.proto

package via.dk.elearn.protobuf;

public interface NewCommentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NewCommentRequest)
    com.google.protobuf.MessageOrBuilder {
}
