// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_user.proto

package via.dk.elearn.protobuf;

public interface NothingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Nothing)
    com.google.protobuf.MessageOrBuilder {
}
