// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_pagination.proto

package via.dk.elearn.protobuf;

public interface PaginationModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PaginationModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pageNumber = 1;</code>
   * @return The pageNumber.
   */
  int getPageNumber();

  /**
   * <code>int32 pageSize = 2;</code>
   * @return The pageSize.
   */
  int getPageSize();
}
