// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_question.proto

package via.dk.elearn.protobuf;

/**
 * Protobuf type {@code QuestionModel}
 */
public final class QuestionModel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:QuestionModel)
    QuestionModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuestionModel.newBuilder() to construct.
  private QuestionModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuestionModel() {
    title_ = "";
    body_ = "";
    description_ = "";
    url_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuestionModel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuestionModel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            body_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          case 50: {
            via.dk.elearn.protobuf.DateModel.Builder subBuilder = null;
            if (dateCreated_ != null) {
              subBuilder = dateCreated_.toBuilder();
            }
            dateCreated_ = input.readMessage(via.dk.elearn.protobuf.DateModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateCreated_);
              dateCreated_ = subBuilder.buildPartial();
            }

            break;
          }
          case 56: {

            correctAnswer_ = input.readBool();
            break;
          }
          case 66: {
            via.dk.elearn.protobuf.StudentModel.Builder subBuilder = null;
            if (student_ != null) {
              subBuilder = student_.toBuilder();
            }
            student_ = input.readMessage(via.dk.elearn.protobuf.StudentModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(student_);
              student_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.dk.elearn.protobuf.RpcQuestion.internal_static_QuestionModel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.dk.elearn.protobuf.RpcQuestion.internal_static_QuestionModel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.dk.elearn.protobuf.QuestionModel.class, via.dk.elearn.protobuf.QuestionModel.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 3;
  private volatile java.lang.Object body_;
  /**
   * <code>string body = 3;</code>
   * @return The body.
   */
  @java.lang.Override
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_FIELD_NUMBER = 5;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 5;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 5;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATECREATED_FIELD_NUMBER = 6;
  private via.dk.elearn.protobuf.DateModel dateCreated_;
  /**
   * <code>.DateModel dateCreated = 6;</code>
   * @return Whether the dateCreated field is set.
   */
  @java.lang.Override
  public boolean hasDateCreated() {
    return dateCreated_ != null;
  }
  /**
   * <code>.DateModel dateCreated = 6;</code>
   * @return The dateCreated.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.DateModel getDateCreated() {
    return dateCreated_ == null ? via.dk.elearn.protobuf.DateModel.getDefaultInstance() : dateCreated_;
  }
  /**
   * <code>.DateModel dateCreated = 6;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.DateModelOrBuilder getDateCreatedOrBuilder() {
    return getDateCreated();
  }

  public static final int CORRECTANSWER_FIELD_NUMBER = 7;
  private boolean correctAnswer_;
  /**
   * <code>bool correctAnswer = 7;</code>
   * @return The correctAnswer.
   */
  @java.lang.Override
  public boolean getCorrectAnswer() {
    return correctAnswer_;
  }

  public static final int STUDENT_FIELD_NUMBER = 8;
  private via.dk.elearn.protobuf.StudentModel student_;
  /**
   * <code>.StudentModel student = 8;</code>
   * @return Whether the student field is set.
   */
  @java.lang.Override
  public boolean hasStudent() {
    return student_ != null;
  }
  /**
   * <code>.StudentModel student = 8;</code>
   * @return The student.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.StudentModel getStudent() {
    return student_ == null ? via.dk.elearn.protobuf.StudentModel.getDefaultInstance() : student_;
  }
  /**
   * <code>.StudentModel student = 8;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.StudentModelOrBuilder getStudentOrBuilder() {
    return getStudent();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, body_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, url_);
    }
    if (dateCreated_ != null) {
      output.writeMessage(6, getDateCreated());
    }
    if (correctAnswer_ != false) {
      output.writeBool(7, correctAnswer_);
    }
    if (student_ != null) {
      output.writeMessage(8, getStudent());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, body_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(url_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, url_);
    }
    if (dateCreated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDateCreated());
    }
    if (correctAnswer_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, correctAnswer_);
    }
    if (student_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getStudent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.dk.elearn.protobuf.QuestionModel)) {
      return super.equals(obj);
    }
    via.dk.elearn.protobuf.QuestionModel other = (via.dk.elearn.protobuf.QuestionModel) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (hasDateCreated() != other.hasDateCreated()) return false;
    if (hasDateCreated()) {
      if (!getDateCreated()
          .equals(other.getDateCreated())) return false;
    }
    if (getCorrectAnswer()
        != other.getCorrectAnswer()) return false;
    if (hasStudent() != other.hasStudent()) return false;
    if (hasStudent()) {
      if (!getStudent()
          .equals(other.getStudent())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    if (hasDateCreated()) {
      hash = (37 * hash) + DATECREATED_FIELD_NUMBER;
      hash = (53 * hash) + getDateCreated().hashCode();
    }
    hash = (37 * hash) + CORRECTANSWER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCorrectAnswer());
    if (hasStudent()) {
      hash = (37 * hash) + STUDENT_FIELD_NUMBER;
      hash = (53 * hash) + getStudent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.QuestionModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.dk.elearn.protobuf.QuestionModel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code QuestionModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:QuestionModel)
      via.dk.elearn.protobuf.QuestionModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.dk.elearn.protobuf.RpcQuestion.internal_static_QuestionModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.dk.elearn.protobuf.RpcQuestion.internal_static_QuestionModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.dk.elearn.protobuf.QuestionModel.class, via.dk.elearn.protobuf.QuestionModel.Builder.class);
    }

    // Construct using via.dk.elearn.protobuf.QuestionModel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      title_ = "";

      body_ = "";

      description_ = "";

      url_ = "";

      if (dateCreatedBuilder_ == null) {
        dateCreated_ = null;
      } else {
        dateCreated_ = null;
        dateCreatedBuilder_ = null;
      }
      correctAnswer_ = false;

      if (studentBuilder_ == null) {
        student_ = null;
      } else {
        student_ = null;
        studentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.dk.elearn.protobuf.RpcQuestion.internal_static_QuestionModel_descriptor;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.QuestionModel getDefaultInstanceForType() {
      return via.dk.elearn.protobuf.QuestionModel.getDefaultInstance();
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.QuestionModel build() {
      via.dk.elearn.protobuf.QuestionModel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.QuestionModel buildPartial() {
      via.dk.elearn.protobuf.QuestionModel result = new via.dk.elearn.protobuf.QuestionModel(this);
      result.id_ = id_;
      result.title_ = title_;
      result.body_ = body_;
      result.description_ = description_;
      result.url_ = url_;
      if (dateCreatedBuilder_ == null) {
        result.dateCreated_ = dateCreated_;
      } else {
        result.dateCreated_ = dateCreatedBuilder_.build();
      }
      result.correctAnswer_ = correctAnswer_;
      if (studentBuilder_ == null) {
        result.student_ = student_;
      } else {
        result.student_ = studentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.dk.elearn.protobuf.QuestionModel) {
        return mergeFrom((via.dk.elearn.protobuf.QuestionModel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.dk.elearn.protobuf.QuestionModel other) {
      if (other == via.dk.elearn.protobuf.QuestionModel.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      if (other.hasDateCreated()) {
        mergeDateCreated(other.getDateCreated());
      }
      if (other.getCorrectAnswer() != false) {
        setCorrectAnswer(other.getCorrectAnswer());
      }
      if (other.hasStudent()) {
        mergeStudent(other.getStudent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.dk.elearn.protobuf.QuestionModel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.dk.elearn.protobuf.QuestionModel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <code>string body = 3;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body = 3;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body = 3;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string body = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <code>string body = 3;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      body_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 5;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 5;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 5;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 5;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.DateModel dateCreated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder> dateCreatedBuilder_;
    /**
     * <code>.DateModel dateCreated = 6;</code>
     * @return Whether the dateCreated field is set.
     */
    public boolean hasDateCreated() {
      return dateCreatedBuilder_ != null || dateCreated_ != null;
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     * @return The dateCreated.
     */
    public via.dk.elearn.protobuf.DateModel getDateCreated() {
      if (dateCreatedBuilder_ == null) {
        return dateCreated_ == null ? via.dk.elearn.protobuf.DateModel.getDefaultInstance() : dateCreated_;
      } else {
        return dateCreatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     */
    public Builder setDateCreated(via.dk.elearn.protobuf.DateModel value) {
      if (dateCreatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateCreated_ = value;
        onChanged();
      } else {
        dateCreatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     */
    public Builder setDateCreated(
        via.dk.elearn.protobuf.DateModel.Builder builderForValue) {
      if (dateCreatedBuilder_ == null) {
        dateCreated_ = builderForValue.build();
        onChanged();
      } else {
        dateCreatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     */
    public Builder mergeDateCreated(via.dk.elearn.protobuf.DateModel value) {
      if (dateCreatedBuilder_ == null) {
        if (dateCreated_ != null) {
          dateCreated_ =
            via.dk.elearn.protobuf.DateModel.newBuilder(dateCreated_).mergeFrom(value).buildPartial();
        } else {
          dateCreated_ = value;
        }
        onChanged();
      } else {
        dateCreatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     */
    public Builder clearDateCreated() {
      if (dateCreatedBuilder_ == null) {
        dateCreated_ = null;
        onChanged();
      } else {
        dateCreated_ = null;
        dateCreatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     */
    public via.dk.elearn.protobuf.DateModel.Builder getDateCreatedBuilder() {
      
      onChanged();
      return getDateCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     */
    public via.dk.elearn.protobuf.DateModelOrBuilder getDateCreatedOrBuilder() {
      if (dateCreatedBuilder_ != null) {
        return dateCreatedBuilder_.getMessageOrBuilder();
      } else {
        return dateCreated_ == null ?
            via.dk.elearn.protobuf.DateModel.getDefaultInstance() : dateCreated_;
      }
    }
    /**
     * <code>.DateModel dateCreated = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder> 
        getDateCreatedFieldBuilder() {
      if (dateCreatedBuilder_ == null) {
        dateCreatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.DateModel, via.dk.elearn.protobuf.DateModel.Builder, via.dk.elearn.protobuf.DateModelOrBuilder>(
                getDateCreated(),
                getParentForChildren(),
                isClean());
        dateCreated_ = null;
      }
      return dateCreatedBuilder_;
    }

    private boolean correctAnswer_ ;
    /**
     * <code>bool correctAnswer = 7;</code>
     * @return The correctAnswer.
     */
    @java.lang.Override
    public boolean getCorrectAnswer() {
      return correctAnswer_;
    }
    /**
     * <code>bool correctAnswer = 7;</code>
     * @param value The correctAnswer to set.
     * @return This builder for chaining.
     */
    public Builder setCorrectAnswer(boolean value) {
      
      correctAnswer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool correctAnswer = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorrectAnswer() {
      
      correctAnswer_ = false;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.StudentModel student_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.StudentModel, via.dk.elearn.protobuf.StudentModel.Builder, via.dk.elearn.protobuf.StudentModelOrBuilder> studentBuilder_;
    /**
     * <code>.StudentModel student = 8;</code>
     * @return Whether the student field is set.
     */
    public boolean hasStudent() {
      return studentBuilder_ != null || student_ != null;
    }
    /**
     * <code>.StudentModel student = 8;</code>
     * @return The student.
     */
    public via.dk.elearn.protobuf.StudentModel getStudent() {
      if (studentBuilder_ == null) {
        return student_ == null ? via.dk.elearn.protobuf.StudentModel.getDefaultInstance() : student_;
      } else {
        return studentBuilder_.getMessage();
      }
    }
    /**
     * <code>.StudentModel student = 8;</code>
     */
    public Builder setStudent(via.dk.elearn.protobuf.StudentModel value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        student_ = value;
        onChanged();
      } else {
        studentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.StudentModel student = 8;</code>
     */
    public Builder setStudent(
        via.dk.elearn.protobuf.StudentModel.Builder builderForValue) {
      if (studentBuilder_ == null) {
        student_ = builderForValue.build();
        onChanged();
      } else {
        studentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.StudentModel student = 8;</code>
     */
    public Builder mergeStudent(via.dk.elearn.protobuf.StudentModel value) {
      if (studentBuilder_ == null) {
        if (student_ != null) {
          student_ =
            via.dk.elearn.protobuf.StudentModel.newBuilder(student_).mergeFrom(value).buildPartial();
        } else {
          student_ = value;
        }
        onChanged();
      } else {
        studentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.StudentModel student = 8;</code>
     */
    public Builder clearStudent() {
      if (studentBuilder_ == null) {
        student_ = null;
        onChanged();
      } else {
        student_ = null;
        studentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.StudentModel student = 8;</code>
     */
    public via.dk.elearn.protobuf.StudentModel.Builder getStudentBuilder() {
      
      onChanged();
      return getStudentFieldBuilder().getBuilder();
    }
    /**
     * <code>.StudentModel student = 8;</code>
     */
    public via.dk.elearn.protobuf.StudentModelOrBuilder getStudentOrBuilder() {
      if (studentBuilder_ != null) {
        return studentBuilder_.getMessageOrBuilder();
      } else {
        return student_ == null ?
            via.dk.elearn.protobuf.StudentModel.getDefaultInstance() : student_;
      }
    }
    /**
     * <code>.StudentModel student = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.StudentModel, via.dk.elearn.protobuf.StudentModel.Builder, via.dk.elearn.protobuf.StudentModelOrBuilder> 
        getStudentFieldBuilder() {
      if (studentBuilder_ == null) {
        studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.StudentModel, via.dk.elearn.protobuf.StudentModel.Builder, via.dk.elearn.protobuf.StudentModelOrBuilder>(
                getStudent(),
                getParentForChildren(),
                isClean());
        student_ = null;
      }
      return studentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:QuestionModel)
  }

  // @@protoc_insertion_point(class_scope:QuestionModel)
  private static final via.dk.elearn.protobuf.QuestionModel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.dk.elearn.protobuf.QuestionModel();
  }

  public static via.dk.elearn.protobuf.QuestionModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuestionModel>
      PARSER = new com.google.protobuf.AbstractParser<QuestionModel>() {
    @java.lang.Override
    public QuestionModel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuestionModel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuestionModel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuestionModel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.dk.elearn.protobuf.QuestionModel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

