// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_question.proto

package via.dk.elearn.protobuf;

public interface QuestionModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QuestionModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string body = 3;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string url = 5;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 5;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>.DateModel dateCreated = 6;</code>
   * @return Whether the dateCreated field is set.
   */
  boolean hasDateCreated();
  /**
   * <code>.DateModel dateCreated = 6;</code>
   * @return The dateCreated.
   */
  via.dk.elearn.protobuf.DateModel getDateCreated();
  /**
   * <code>.DateModel dateCreated = 6;</code>
   */
  via.dk.elearn.protobuf.DateModelOrBuilder getDateCreatedOrBuilder();

  /**
   * <code>bool correctAnswer = 7;</code>
   * @return The correctAnswer.
   */
  boolean getCorrectAnswer();

  /**
   * <code>.StudentModel student = 8;</code>
   * @return Whether the student field is set.
   */
  boolean hasStudent();
  /**
   * <code>.StudentModel student = 8;</code>
   * @return The student.
   */
  via.dk.elearn.protobuf.StudentModel getStudent();
  /**
   * <code>.StudentModel student = 8;</code>
   */
  via.dk.elearn.protobuf.StudentModelOrBuilder getStudentOrBuilder();
}
