// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_question.proto

package via.dk.elearn.protobuf;

public interface QuestionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QuestionResponse)
    com.google.protobuf.MessageOrBuilder {
}
