// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_question.proto

package via.dk.elearn.protobuf;

public interface QuestionUserIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QuestionUserId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
