// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_answer.proto

package via.dk.elearn.protobuf;

public final class RpcAnswer {
  private RpcAnswer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewAnswerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewAnswerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnswerModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnswerModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnswerId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnswerId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020rpc_answer.proto\032\016rpc_date.proto\032\016rpc_" +
      "user.proto\032\022rpc_question.proto\"\022\n\020NewAns" +
      "werRequest\"\220\001\n\013AnswerModel\022\n\n\002id\030\001 \001(\003\022\032" +
      "\n\006author\030\002 \001(\0132\n.UserModel\022 \n\010question\030\003" +
      " \001(\0132\016.QuestionModel\022\014\n\004text\030\004 \001(\t\022\030\n\004da" +
      "te\030\005 \001(\0132\n.DateModel\022\017\n\007correct\030\006 \001(\010\"\026\n" +
      "\010AnswerId\022\n\n\002id\030\001 \001(\0032\306\001\n\rAnswerService\022" +
      "-\n\017CreateNewAnswer\022\014.AnswerModel\032\014.Answe" +
      "rModel\0224\n\025GetAnswerByQuestionId\022\013.Questi" +
      "onId\032\014.AnswerModel0\001\022(\n\rGetAnswerById\022\t." +
      "AnswerId\032\014.AnswerModel\022&\n\014DeleteAnswer\022\014" +
      ".AnswerModel\032\010.NothingB\032\n\026via.dk.elearn." +
      "protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.dk.elearn.protobuf.RpcDate.getDescriptor(),
          via.dk.elearn.protobuf.RpcUser.getDescriptor(),
          via.dk.elearn.protobuf.RpcQuestion.getDescriptor(),
        });
    internal_static_NewAnswerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewAnswerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewAnswerRequest_descriptor,
        new java.lang.String[] { });
    internal_static_AnswerModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnswerModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnswerModel_descriptor,
        new java.lang.String[] { "Id", "Author", "Question", "Text", "Date", "Correct", });
    internal_static_AnswerId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AnswerId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnswerId_descriptor,
        new java.lang.String[] { "Id", });
    via.dk.elearn.protobuf.RpcDate.getDescriptor();
    via.dk.elearn.protobuf.RpcUser.getDescriptor();
    via.dk.elearn.protobuf.RpcQuestion.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
