// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_country.proto

package via.dk.elearn.protobuf;

public final class RpcCountry {
  private RpcCountry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CountryModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CountryModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CountryId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CountryId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CountryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CountryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021rpc_country.proto\"(\n\014CountryModel\022\n\n\002i" +
      "d\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\"\027\n\tCountryId\022\n\n\002id" +
      "\030\001 \001(\003\"\020\n\016CountryRequest2o\n\016CountryServi" +
      "ce\0220\n\014GetCountries\022\017.CountryRequest\032\r.Co" +
      "untryModel0\001\022+\n\016GetCountryById\022\n.Country" +
      "Id\032\r.CountryModelB\032\n\026via.dk.elearn.proto" +
      "bufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CountryModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CountryModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CountryModel_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_CountryId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CountryId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CountryId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CountryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CountryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CountryRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
