// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_comment.proto

package via.dk.elearn.protobuf;

public final class RpcComment {
  private RpcComment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommentId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommentId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021rpc_comment.proto\032\016rpc_date.proto\032\016rpc" +
      "_user.proto\032\021rpc_lecture.proto\"\023\n\021NewCom" +
      "mentRequest\"~\n\014CommentModel\022\n\n\002id\030\001 \001(\003\022" +
      "\032\n\006author\030\002 \001(\0132\n.UserModel\022\036\n\007lecture\030\003" +
      " \001(\0132\r.LectureModel\022\014\n\004text\030\004 \001(\t\022\030\n\004dat" +
      "e\030\005 \001(\0132\n.DateModel\"\027\n\tCommentId\022\n\n\002id\030\001" +
      " \001(\0032\206\002\n\016CommentService\0225\n\016GetAllComment" +
      "s\022\022.NewCommentRequest\032\r.CommentModel0\001\0220" +
      "\n\020CreateNewComment\022\r.CommentModel\032\r.Comm" +
      "entModel\0224\n\025GetCommentByLectureId\022\n.Lect" +
      "ureId\032\r.CommentModel0\001\022+\n\016GetCommentById" +
      "\022\n.CommentId\032\r.CommentModel\022(\n\rDeleteCom" +
      "ment\022\r.CommentModel\032\010.NothingB\032\n\026via.dk." +
      "elearn.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.dk.elearn.protobuf.RpcDate.getDescriptor(),
          via.dk.elearn.protobuf.RpcUser.getDescriptor(),
          via.dk.elearn.protobuf.RpcLecture.getDescriptor(),
        });
    internal_static_NewCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NewCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewCommentRequest_descriptor,
        new java.lang.String[] { });
    internal_static_CommentModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CommentModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentModel_descriptor,
        new java.lang.String[] { "Id", "Author", "Lecture", "Text", "Date", });
    internal_static_CommentId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CommentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommentId_descriptor,
        new java.lang.String[] { "Id", });
    via.dk.elearn.protobuf.RpcDate.getDescriptor();
    via.dk.elearn.protobuf.RpcUser.getDescriptor();
    via.dk.elearn.protobuf.RpcLecture.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
