// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_lecture.proto

package via.dk.elearn.protobuf;

public final class RpcLecture {
  private RpcLecture() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LectureUserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LectureUserId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LectureUrl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LectureUrl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LectureId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LectureId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LectureModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LectureModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LectureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LectureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021rpc_lecture.proto\032\016rpc_date.proto\032\021rpc" +
      "_teacher.proto\032\024rpc_pagination.proto\"\037\n\r" +
      "LectureUserId\022\016\n\006userId\030\001 \001(\003\"\031\n\nLecture" +
      "Url\022\013\n\003url\030\001 \001(\t\"\027\n\tLectureId\022\n\n\002id\030\001 \001(" +
      "\003\"\242\001\n\014LectureModel\022\n\n\002id\030\001 \001(\003\022\014\n\004body\030\002" +
      " \001(\t\022\r\n\005title\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\r\n\005imag" +
      "e\030\005 \001(\t\022\023\n\013description\030\006 \001(\t\022\036\n\007teacher\030" +
      "\007 \001(\0132\r.TeacherModel\022\030\n\004date\030\010 \001(\0132\n.Dat" +
      "eModel\"\021\n\017LectureResponse2\242\003\n\016LectureSer" +
      "vice\022(\n\nGetLecture\022\013.LectureUrl\032\r.Lectur" +
      "eModel\0223\n\016GetAllLectures\022\020.PaginationMod" +
      "el\032\r.LectureModel0\001\0220\n\020CreateNewLecture\022" +
      "\r.LectureModel\032\r.LectureModel\022+\n\016GetLect" +
      "ureById\022\n.LectureId\032\r.LectureModel\0225\n\022Ge" +
      "tLectureByUserId\022\016.LectureUserId\032\r.Lectu" +
      "reModel0\001\022<\n\031GetUpvotedLectureByUserId\022\016" +
      ".LectureUserId\032\r.LectureModel0\001\022+\n\013EditL" +
      "ecture\022\r.LectureModel\032\r.LectureModel\0220\n\r" +
      "DeleteLecture\022\r.LectureModel\032\020.LectureRe" +
      "sponseB\032\n\026via.dk.elearn.protobufP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.dk.elearn.protobuf.RpcDate.getDescriptor(),
          via.dk.elearn.protobuf.RpcTeacher.getDescriptor(),
          via.dk.elearn.protobuf.RpcPagination.getDescriptor(),
        });
    internal_static_LectureUserId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LectureUserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LectureUserId_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_LectureUrl_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LectureUrl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LectureUrl_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_LectureId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LectureId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LectureId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_LectureModel_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LectureModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LectureModel_descriptor,
        new java.lang.String[] { "Id", "Body", "Title", "Url", "Image", "Description", "Teacher", "Date", });
    internal_static_LectureResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LectureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LectureResponse_descriptor,
        new java.lang.String[] { });
    via.dk.elearn.protobuf.RpcDate.getDescriptor();
    via.dk.elearn.protobuf.RpcTeacher.getDescriptor();
    via.dk.elearn.protobuf.RpcPagination.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
