// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_moderator.proto

package via.dk.elearn.protobuf;

public final class RpcModerator {
  private RpcModerator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModeratorModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModeratorModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModeratorUsername_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModeratorUsername_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023rpc_moderator.proto\"\243\001\n\016ModeratorModel" +
      "\022\n\n\002id\030\001 \001(\003\022\020\n\010username\030\002 \001(\t\022\r\n\005email\030" +
      "\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022\r\n" +
      "\005image\030\006 \001(\t\022\014\n\004role\030\007 \001(\t\022\025\n\rsecurityLe" +
      "vel\030\010 \001(\005\022\020\n\010approved\030\t \001(\010\"%\n\021Moderator" +
      "Username\022\020\n\010username\030\001 \001(\t2Q\n\020ModeratorS" +
      "ervice\022=\n\026getModeratorByUsername\022\022.Moder" +
      "atorUsername\032\017.ModeratorModelB\032\n\026via.dk." +
      "elearn.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ModeratorModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ModeratorModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModeratorModel_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "Name", "Password", "Image", "Role", "SecurityLevel", "Approved", });
    internal_static_ModeratorUsername_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ModeratorUsername_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModeratorUsername_descriptor,
        new java.lang.String[] { "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
