// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_question.proto

package via.dk.elearn.protobuf;

public final class RpcQuestion {
  private RpcQuestion() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestionUserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestionUserId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestionUrl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestionUrl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestionId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestionId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestionModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestionModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022rpc_question.proto\032\024rpc_pagination.pro" +
      "to\032\021rpc_student.proto\032\016rpc_date.proto\" \n" +
      "\016QuestionUserId\022\016\n\006userId\030\001 \001(\003\"\032\n\013Quest" +
      "ionUrl\022\013\n\003url\030\001 \001(\t\"\030\n\nQuestionId\022\n\n\002id\030" +
      "\001 \001(\003\"\262\001\n\rQuestionModel\022\n\n\002id\030\001 \001(\003\022\r\n\005t" +
      "itle\030\002 \001(\t\022\014\n\004body\030\003 \001(\t\022\023\n\013description\030" +
      "\004 \001(\t\022\013\n\003url\030\005 \001(\t\022\037\n\013dateCreated\030\006 \001(\0132" +
      "\n.DateModel\022\025\n\rcorrectAnswer\030\007 \001(\010\022\036\n\007st" +
      "udent\030\010 \001(\0132\r.StudentModel\"\022\n\020QuestionRe" +
      "sponse2\371\002\n\017QuestionService\022+\n\013GetQuestio" +
      "n\022\014.QuestionUrl\032\016.QuestionModel\0225\n\017GetAl" +
      "lQuestions\022\020.PaginationModel\032\016.QuestionM" +
      "odel0\001\0223\n\021CreateNewQuestion\022\016.QuestionMo" +
      "del\032\016.QuestionModel\0229\n\024GetQuestionsByUse" +
      "rId\022\017.QuestionUserId\032\016.QuestionModel0\001\0222" +
      "\n\rDeleteLecture\022\016.QuestionModel\032\021.Questi" +
      "onResponse\022.\n\014EditQuestion\022\016.QuestionMod" +
      "el\032\016.QuestionModel\022.\n\017GetQuestionById\022\013." +
      "QuestionId\032\016.QuestionModelB\032\n\026via.dk.ele" +
      "arn.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.dk.elearn.protobuf.RpcPagination.getDescriptor(),
          via.dk.elearn.protobuf.RpcStudent.getDescriptor(),
          via.dk.elearn.protobuf.RpcDate.getDescriptor(),
        });
    internal_static_QuestionUserId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QuestionUserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestionUserId_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_QuestionUrl_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QuestionUrl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestionUrl_descriptor,
        new java.lang.String[] { "Url", });
    internal_static_QuestionId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_QuestionId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestionId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_QuestionModel_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_QuestionModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestionModel_descriptor,
        new java.lang.String[] { "Id", "Title", "Body", "Description", "Url", "DateCreated", "CorrectAnswer", "Student", });
    internal_static_QuestionResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_QuestionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestionResponse_descriptor,
        new java.lang.String[] { });
    via.dk.elearn.protobuf.RpcPagination.getDescriptor();
    via.dk.elearn.protobuf.RpcStudent.getDescriptor();
    via.dk.elearn.protobuf.RpcDate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
