// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_student.proto

package via.dk.elearn.protobuf;

public final class RpcStudent {
  private RpcStudent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentUsername_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentUsername_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021rpc_student.proto\032\024rpc_university.prot" +
      "o\"#\n\017StudentUsername\022\020\n\010username\030\001 \001(\t\"\307" +
      "\001\n\014StudentModel\022\n\n\002id\030\001 \001(\003\022\020\n\010username\030" +
      "\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\020\n\010pa" +
      "ssword\030\005 \001(\t\022\r\n\005image\030\006 \001(\t\022\014\n\004role\030\007 \001(" +
      "\t\022\025\n\rsecurityLevel\030\010 \001(\005\022$\n\nuniversity\030\t" +
      " \001(\0132\020.UniversityModel\022\020\n\010approved\030\n \001(\010" +
      "2I\n\016StudentService\0227\n\024getStudentByUserna" +
      "me\022\020.StudentUsername\032\r.StudentModelB\032\n\026v" +
      "ia.dk.elearn.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.dk.elearn.protobuf.RpcUniversity.getDescriptor(),
        });
    internal_static_StudentUsername_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StudentUsername_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentUsername_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_StudentModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StudentModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentModel_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "Name", "Password", "Image", "Role", "SecurityLevel", "University", "Approved", });
    via.dk.elearn.protobuf.RpcUniversity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
