// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_university.proto

package via.dk.elearn.protobuf;

public final class RpcUniversity {
  private RpcUniversity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UniversityModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UniversityModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UniversityId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UniversityId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UniversityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UniversityRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024rpc_university.proto\032\021rpc_lecture.prot" +
      "o\"@\n\017UniversityModel\022\n\n\002id\030\001 \001(\003\022\014\n\004name" +
      "\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\"\032\n\014Universit" +
      "yId\022\n\n\002id\030\001 \001(\003\"\023\n\021UniversityRequest2\302\001\n" +
      "\021UniversityService\022<\n\027GetLecturesByUnive" +
      "rsity\022\020.UniversityModel\032\r.LectureModel0\001" +
      "\0229\n\017GetUniversities\022\022.UniversityRequest\032" +
      "\020.UniversityModel0\001\0224\n\021GetUniversityById" +
      "\022\r.UniversityId\032\020.UniversityModelB\032\n\026via" +
      ".dk.elearn.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.dk.elearn.protobuf.RpcLecture.getDescriptor(),
        });
    internal_static_UniversityModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UniversityModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UniversityModel_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", });
    internal_static_UniversityId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UniversityId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UniversityId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UniversityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UniversityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UniversityRequest_descriptor,
        new java.lang.String[] { });
    via.dk.elearn.protobuf.RpcLecture.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
