// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_user.proto

package via.dk.elearn.protobuf;

public final class RpcUser {
  private RpcUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Nothing_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Nothing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016rpc_user.proto\032\024rpc_university.proto\032\021" +
      "rpc_country.proto\"\344\001\n\tUserModel\022\n\n\002id\030\001 " +
      "\001(\003\022\020\n\010username\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\014\n\004" +
      "name\030\004 \001(\t\022\020\n\010password\030\005 \001(\t\022\r\n\005image\030\006 " +
      "\001(\t\022\014\n\004role\030\007 \001(\t\022\025\n\rsecurityLevel\030\010 \001(\005" +
      "\022$\n\nuniversity\030\t \001(\0132\020.UniversityModel\022\020" +
      "\n\010approved\030\n \001(\010\022\036\n\007country\030\013 \001(\0132\r.Coun" +
      "tryModel\"\024\n\006UserId\022\n\n\002id\030\001 \001(\003\"\034\n\010UserNa" +
      "me\022\020\n\010username\030\001 \001(\t\"\024\n\004Name\022\014\n\004name\030\001 \001" +
      "(\t\"\t\n\007Nothing2\232\002\n\013UserService\022\"\n\rGetUser" +
      "ByName\022\005.Name\032\n.UserModel\022*\n\021GetUserByUs" +
      "ername\022\t.UserName\032\n.UserModel\022\'\n\rCreateN" +
      "ewUser\022\n.UserModel\032\n.UserModel\022\"\n\013GetUse" +
      "rByID\022\007.UserId\032\n.UserModel\022$\n\nUpdateUser" +
      "\022\n.UserModel\032\n.UserModel\022\"\n\nDeleteUser\022\n" +
      ".UserModel\032\010.Nothing\022$\n\013GetAllUsers\022\007.Us" +
      "erId\032\n.UserModel0\001B\032\n\026via.dk.elearn.prot" +
      "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.dk.elearn.protobuf.RpcUniversity.getDescriptor(),
          via.dk.elearn.protobuf.RpcCountry.getDescriptor(),
        });
    internal_static_UserModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserModel_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "Name", "Password", "Image", "Role", "SecurityLevel", "University", "Approved", "Country", });
    internal_static_UserId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UserName_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserName_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_Name_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Name_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_Nothing_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Nothing_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Nothing_descriptor,
        new java.lang.String[] { });
    via.dk.elearn.protobuf.RpcUniversity.getDescriptor();
    via.dk.elearn.protobuf.RpcCountry.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
