// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_search.proto

package via.dk.elearn.protobuf;

public interface SearchLecturesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchLecturesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
