// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_search.proto

package via.dk.elearn.protobuf;

public interface SearchUsersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchUsersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
