// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_student.proto

package via.dk.elearn.protobuf;

public interface StudentModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 5;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 5;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string image = 6;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 6;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>string role = 7;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 7;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>int32 securityLevel = 8;</code>
   * @return The securityLevel.
   */
  int getSecurityLevel();

  /**
   * <code>.UniversityModel university = 9;</code>
   * @return Whether the university field is set.
   */
  boolean hasUniversity();
  /**
   * <code>.UniversityModel university = 9;</code>
   * @return The university.
   */
  via.dk.elearn.protobuf.UniversityModel getUniversity();
  /**
   * <code>.UniversityModel university = 9;</code>
   */
  via.dk.elearn.protobuf.UniversityModelOrBuilder getUniversityOrBuilder();

  /**
   * <code>bool approved = 10;</code>
   * @return The approved.
   */
  boolean getApproved();
}
