// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_teacher.proto

package via.dk.elearn.protobuf;

public interface TeacherUsernameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TeacherUsername)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
