// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_university.proto

package via.dk.elearn.protobuf;

public interface UniversityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UniversityRequest)
    com.google.protobuf.MessageOrBuilder {
}
