// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_university.proto

package via.dk.elearn.protobuf;

public interface UniversityIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UniversityId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
