// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_user.proto

package via.dk.elearn.protobuf;

/**
 * Protobuf type {@code UserModel}
 */
public final class UserModel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UserModel)
    UserModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserModel.newBuilder() to construct.
  private UserModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserModel() {
    username_ = "";
    email_ = "";
    name_ = "";
    password_ = "";
    image_ = "";
    role_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserModel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserModel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            image_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            role_ = s;
            break;
          }
          case 64: {

            securityLevel_ = input.readInt32();
            break;
          }
          case 74: {
            via.dk.elearn.protobuf.UniversityModel.Builder subBuilder = null;
            if (university_ != null) {
              subBuilder = university_.toBuilder();
            }
            university_ = input.readMessage(via.dk.elearn.protobuf.UniversityModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(university_);
              university_ = subBuilder.buildPartial();
            }

            break;
          }
          case 80: {

            approved_ = input.readBool();
            break;
          }
          case 90: {
            via.dk.elearn.protobuf.CountryModel.Builder subBuilder = null;
            if (country_ != null) {
              subBuilder = country_.toBuilder();
            }
            country_ = input.readMessage(via.dk.elearn.protobuf.CountryModel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(country_);
              country_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.dk.elearn.protobuf.RpcUser.internal_static_UserModel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.dk.elearn.protobuf.RpcUser.internal_static_UserModel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.dk.elearn.protobuf.UserModel.class, via.dk.elearn.protobuf.UserModel.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;
  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 4;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 5;
  private volatile java.lang.Object password_;
  /**
   * <code>string password = 5;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string password = 5;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_FIELD_NUMBER = 6;
  private volatile java.lang.Object image_;
  /**
   * <code>string image = 6;</code>
   * @return The image.
   */
  @java.lang.Override
  public java.lang.String getImage() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image_ = s;
      return s;
    }
  }
  /**
   * <code>string image = 6;</code>
   * @return The bytes for image.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImageBytes() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      image_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLE_FIELD_NUMBER = 7;
  private volatile java.lang.Object role_;
  /**
   * <code>string role = 7;</code>
   * @return The role.
   */
  @java.lang.Override
  public java.lang.String getRole() {
    java.lang.Object ref = role_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      role_ = s;
      return s;
    }
  }
  /**
   * <code>string role = 7;</code>
   * @return The bytes for role.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoleBytes() {
    java.lang.Object ref = role_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      role_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECURITYLEVEL_FIELD_NUMBER = 8;
  private int securityLevel_;
  /**
   * <code>int32 securityLevel = 8;</code>
   * @return The securityLevel.
   */
  @java.lang.Override
  public int getSecurityLevel() {
    return securityLevel_;
  }

  public static final int UNIVERSITY_FIELD_NUMBER = 9;
  private via.dk.elearn.protobuf.UniversityModel university_;
  /**
   * <code>.UniversityModel university = 9;</code>
   * @return Whether the university field is set.
   */
  @java.lang.Override
  public boolean hasUniversity() {
    return university_ != null;
  }
  /**
   * <code>.UniversityModel university = 9;</code>
   * @return The university.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.UniversityModel getUniversity() {
    return university_ == null ? via.dk.elearn.protobuf.UniversityModel.getDefaultInstance() : university_;
  }
  /**
   * <code>.UniversityModel university = 9;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.UniversityModelOrBuilder getUniversityOrBuilder() {
    return getUniversity();
  }

  public static final int APPROVED_FIELD_NUMBER = 10;
  private boolean approved_;
  /**
   * <code>bool approved = 10;</code>
   * @return The approved.
   */
  @java.lang.Override
  public boolean getApproved() {
    return approved_;
  }

  public static final int COUNTRY_FIELD_NUMBER = 11;
  private via.dk.elearn.protobuf.CountryModel country_;
  /**
   * <code>.CountryModel country = 11;</code>
   * @return Whether the country field is set.
   */
  @java.lang.Override
  public boolean hasCountry() {
    return country_ != null;
  }
  /**
   * <code>.CountryModel country = 11;</code>
   * @return The country.
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.CountryModel getCountry() {
    return country_ == null ? via.dk.elearn.protobuf.CountryModel.getDefaultInstance() : country_;
  }
  /**
   * <code>.CountryModel country = 11;</code>
   */
  @java.lang.Override
  public via.dk.elearn.protobuf.CountryModelOrBuilder getCountryOrBuilder() {
    return getCountry();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, image_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(role_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, role_);
    }
    if (securityLevel_ != 0) {
      output.writeInt32(8, securityLevel_);
    }
    if (university_ != null) {
      output.writeMessage(9, getUniversity());
    }
    if (approved_ != false) {
      output.writeBool(10, approved_);
    }
    if (country_ != null) {
      output.writeMessage(11, getCountry());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, password_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, image_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(role_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, role_);
    }
    if (securityLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, securityLevel_);
    }
    if (university_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getUniversity());
    }
    if (approved_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, approved_);
    }
    if (country_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCountry());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.dk.elearn.protobuf.UserModel)) {
      return super.equals(obj);
    }
    via.dk.elearn.protobuf.UserModel other = (via.dk.elearn.protobuf.UserModel) obj;

    if (getId()
        != other.getId()) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getImage()
        .equals(other.getImage())) return false;
    if (!getRole()
        .equals(other.getRole())) return false;
    if (getSecurityLevel()
        != other.getSecurityLevel()) return false;
    if (hasUniversity() != other.hasUniversity()) return false;
    if (hasUniversity()) {
      if (!getUniversity()
          .equals(other.getUniversity())) return false;
    }
    if (getApproved()
        != other.getApproved()) return false;
    if (hasCountry() != other.hasCountry()) return false;
    if (hasCountry()) {
      if (!getCountry()
          .equals(other.getCountry())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getImage().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + getRole().hashCode();
    hash = (37 * hash) + SECURITYLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getSecurityLevel();
    if (hasUniversity()) {
      hash = (37 * hash) + UNIVERSITY_FIELD_NUMBER;
      hash = (53 * hash) + getUniversity().hashCode();
    }
    hash = (37 * hash) + APPROVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getApproved());
    if (hasCountry()) {
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.dk.elearn.protobuf.UserModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.UserModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.UserModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.dk.elearn.protobuf.UserModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.dk.elearn.protobuf.UserModel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UserModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UserModel)
      via.dk.elearn.protobuf.UserModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.dk.elearn.protobuf.RpcUser.internal_static_UserModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.dk.elearn.protobuf.RpcUser.internal_static_UserModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.dk.elearn.protobuf.UserModel.class, via.dk.elearn.protobuf.UserModel.Builder.class);
    }

    // Construct using via.dk.elearn.protobuf.UserModel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      username_ = "";

      email_ = "";

      name_ = "";

      password_ = "";

      image_ = "";

      role_ = "";

      securityLevel_ = 0;

      if (universityBuilder_ == null) {
        university_ = null;
      } else {
        university_ = null;
        universityBuilder_ = null;
      }
      approved_ = false;

      if (countryBuilder_ == null) {
        country_ = null;
      } else {
        country_ = null;
        countryBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.dk.elearn.protobuf.RpcUser.internal_static_UserModel_descriptor;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.UserModel getDefaultInstanceForType() {
      return via.dk.elearn.protobuf.UserModel.getDefaultInstance();
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.UserModel build() {
      via.dk.elearn.protobuf.UserModel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.dk.elearn.protobuf.UserModel buildPartial() {
      via.dk.elearn.protobuf.UserModel result = new via.dk.elearn.protobuf.UserModel(this);
      result.id_ = id_;
      result.username_ = username_;
      result.email_ = email_;
      result.name_ = name_;
      result.password_ = password_;
      result.image_ = image_;
      result.role_ = role_;
      result.securityLevel_ = securityLevel_;
      if (universityBuilder_ == null) {
        result.university_ = university_;
      } else {
        result.university_ = universityBuilder_.build();
      }
      result.approved_ = approved_;
      if (countryBuilder_ == null) {
        result.country_ = country_;
      } else {
        result.country_ = countryBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.dk.elearn.protobuf.UserModel) {
        return mergeFrom((via.dk.elearn.protobuf.UserModel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.dk.elearn.protobuf.UserModel other) {
      if (other == via.dk.elearn.protobuf.UserModel.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (!other.getImage().isEmpty()) {
        image_ = other.image_;
        onChanged();
      }
      if (!other.getRole().isEmpty()) {
        role_ = other.role_;
        onChanged();
      }
      if (other.getSecurityLevel() != 0) {
        setSecurityLevel(other.getSecurityLevel());
      }
      if (other.hasUniversity()) {
        mergeUniversity(other.getUniversity());
      }
      if (other.getApproved() != false) {
        setApproved(other.getApproved());
      }
      if (other.hasCountry()) {
        mergeCountry(other.getCountry());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.dk.elearn.protobuf.UserModel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.dk.elearn.protobuf.UserModel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string password = 5;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string password = 5;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string password = 5;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string password = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string password = 5;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object image_ = "";
    /**
     * <code>string image = 6;</code>
     * @return The image.
     */
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string image = 6;</code>
     * @return The bytes for image.
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string image = 6;</code>
     * @param value The image to set.
     * @return This builder for chaining.
     */
    public Builder setImage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      image_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string image = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearImage() {
      
      image_ = getDefaultInstance().getImage();
      onChanged();
      return this;
    }
    /**
     * <code>string image = 6;</code>
     * @param value The bytes for image to set.
     * @return This builder for chaining.
     */
    public Builder setImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      image_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object role_ = "";
    /**
     * <code>string role = 7;</code>
     * @return The role.
     */
    public java.lang.String getRole() {
      java.lang.Object ref = role_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        role_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string role = 7;</code>
     * @return The bytes for role.
     */
    public com.google.protobuf.ByteString
        getRoleBytes() {
      java.lang.Object ref = role_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string role = 7;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string role = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      
      role_ = getDefaultInstance().getRole();
      onChanged();
      return this;
    }
    /**
     * <code>string role = 7;</code>
     * @param value The bytes for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      role_ = value;
      onChanged();
      return this;
    }

    private int securityLevel_ ;
    /**
     * <code>int32 securityLevel = 8;</code>
     * @return The securityLevel.
     */
    @java.lang.Override
    public int getSecurityLevel() {
      return securityLevel_;
    }
    /**
     * <code>int32 securityLevel = 8;</code>
     * @param value The securityLevel to set.
     * @return This builder for chaining.
     */
    public Builder setSecurityLevel(int value) {
      
      securityLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 securityLevel = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecurityLevel() {
      
      securityLevel_ = 0;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.UniversityModel university_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.UniversityModel, via.dk.elearn.protobuf.UniversityModel.Builder, via.dk.elearn.protobuf.UniversityModelOrBuilder> universityBuilder_;
    /**
     * <code>.UniversityModel university = 9;</code>
     * @return Whether the university field is set.
     */
    public boolean hasUniversity() {
      return universityBuilder_ != null || university_ != null;
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     * @return The university.
     */
    public via.dk.elearn.protobuf.UniversityModel getUniversity() {
      if (universityBuilder_ == null) {
        return university_ == null ? via.dk.elearn.protobuf.UniversityModel.getDefaultInstance() : university_;
      } else {
        return universityBuilder_.getMessage();
      }
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     */
    public Builder setUniversity(via.dk.elearn.protobuf.UniversityModel value) {
      if (universityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        university_ = value;
        onChanged();
      } else {
        universityBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     */
    public Builder setUniversity(
        via.dk.elearn.protobuf.UniversityModel.Builder builderForValue) {
      if (universityBuilder_ == null) {
        university_ = builderForValue.build();
        onChanged();
      } else {
        universityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     */
    public Builder mergeUniversity(via.dk.elearn.protobuf.UniversityModel value) {
      if (universityBuilder_ == null) {
        if (university_ != null) {
          university_ =
            via.dk.elearn.protobuf.UniversityModel.newBuilder(university_).mergeFrom(value).buildPartial();
        } else {
          university_ = value;
        }
        onChanged();
      } else {
        universityBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     */
    public Builder clearUniversity() {
      if (universityBuilder_ == null) {
        university_ = null;
        onChanged();
      } else {
        university_ = null;
        universityBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     */
    public via.dk.elearn.protobuf.UniversityModel.Builder getUniversityBuilder() {
      
      onChanged();
      return getUniversityFieldBuilder().getBuilder();
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     */
    public via.dk.elearn.protobuf.UniversityModelOrBuilder getUniversityOrBuilder() {
      if (universityBuilder_ != null) {
        return universityBuilder_.getMessageOrBuilder();
      } else {
        return university_ == null ?
            via.dk.elearn.protobuf.UniversityModel.getDefaultInstance() : university_;
      }
    }
    /**
     * <code>.UniversityModel university = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.UniversityModel, via.dk.elearn.protobuf.UniversityModel.Builder, via.dk.elearn.protobuf.UniversityModelOrBuilder> 
        getUniversityFieldBuilder() {
      if (universityBuilder_ == null) {
        universityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.UniversityModel, via.dk.elearn.protobuf.UniversityModel.Builder, via.dk.elearn.protobuf.UniversityModelOrBuilder>(
                getUniversity(),
                getParentForChildren(),
                isClean());
        university_ = null;
      }
      return universityBuilder_;
    }

    private boolean approved_ ;
    /**
     * <code>bool approved = 10;</code>
     * @return The approved.
     */
    @java.lang.Override
    public boolean getApproved() {
      return approved_;
    }
    /**
     * <code>bool approved = 10;</code>
     * @param value The approved to set.
     * @return This builder for chaining.
     */
    public Builder setApproved(boolean value) {
      
      approved_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool approved = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearApproved() {
      
      approved_ = false;
      onChanged();
      return this;
    }

    private via.dk.elearn.protobuf.CountryModel country_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.CountryModel, via.dk.elearn.protobuf.CountryModel.Builder, via.dk.elearn.protobuf.CountryModelOrBuilder> countryBuilder_;
    /**
     * <code>.CountryModel country = 11;</code>
     * @return Whether the country field is set.
     */
    public boolean hasCountry() {
      return countryBuilder_ != null || country_ != null;
    }
    /**
     * <code>.CountryModel country = 11;</code>
     * @return The country.
     */
    public via.dk.elearn.protobuf.CountryModel getCountry() {
      if (countryBuilder_ == null) {
        return country_ == null ? via.dk.elearn.protobuf.CountryModel.getDefaultInstance() : country_;
      } else {
        return countryBuilder_.getMessage();
      }
    }
    /**
     * <code>.CountryModel country = 11;</code>
     */
    public Builder setCountry(via.dk.elearn.protobuf.CountryModel value) {
      if (countryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        country_ = value;
        onChanged();
      } else {
        countryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.CountryModel country = 11;</code>
     */
    public Builder setCountry(
        via.dk.elearn.protobuf.CountryModel.Builder builderForValue) {
      if (countryBuilder_ == null) {
        country_ = builderForValue.build();
        onChanged();
      } else {
        countryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.CountryModel country = 11;</code>
     */
    public Builder mergeCountry(via.dk.elearn.protobuf.CountryModel value) {
      if (countryBuilder_ == null) {
        if (country_ != null) {
          country_ =
            via.dk.elearn.protobuf.CountryModel.newBuilder(country_).mergeFrom(value).buildPartial();
        } else {
          country_ = value;
        }
        onChanged();
      } else {
        countryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.CountryModel country = 11;</code>
     */
    public Builder clearCountry() {
      if (countryBuilder_ == null) {
        country_ = null;
        onChanged();
      } else {
        country_ = null;
        countryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.CountryModel country = 11;</code>
     */
    public via.dk.elearn.protobuf.CountryModel.Builder getCountryBuilder() {
      
      onChanged();
      return getCountryFieldBuilder().getBuilder();
    }
    /**
     * <code>.CountryModel country = 11;</code>
     */
    public via.dk.elearn.protobuf.CountryModelOrBuilder getCountryOrBuilder() {
      if (countryBuilder_ != null) {
        return countryBuilder_.getMessageOrBuilder();
      } else {
        return country_ == null ?
            via.dk.elearn.protobuf.CountryModel.getDefaultInstance() : country_;
      }
    }
    /**
     * <code>.CountryModel country = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.dk.elearn.protobuf.CountryModel, via.dk.elearn.protobuf.CountryModel.Builder, via.dk.elearn.protobuf.CountryModelOrBuilder> 
        getCountryFieldBuilder() {
      if (countryBuilder_ == null) {
        countryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.dk.elearn.protobuf.CountryModel, via.dk.elearn.protobuf.CountryModel.Builder, via.dk.elearn.protobuf.CountryModelOrBuilder>(
                getCountry(),
                getParentForChildren(),
                isClean());
        country_ = null;
      }
      return countryBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UserModel)
  }

  // @@protoc_insertion_point(class_scope:UserModel)
  private static final via.dk.elearn.protobuf.UserModel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.dk.elearn.protobuf.UserModel();
  }

  public static via.dk.elearn.protobuf.UserModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserModel>
      PARSER = new com.google.protobuf.AbstractParser<UserModel>() {
    @java.lang.Override
    public UserModel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserModel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserModel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserModel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.dk.elearn.protobuf.UserModel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

